### Get all
GET http://localhost:3001/api/players

### Get single
GET http://localhost:30001/api/players/2

### Create new
POST http://localhost:3001/api/players
Content-Type: application/json; charset=utf-8

{
  "name": "Connor Mcdavid23",
  "position": "Center",
  "jersey": 97
}

### UPDATE
PUT http://localhost:3001/api/players/30
Content-Type: application/json; charset=utf-8

{
  "name": "Sidney Crosby",
  "position": "Center",
  "jersey": 87
}






### DELETE
DELETE  http://localhost:3001/api/players/2
Content-Type: application/json

